### ISSUE TITLE
Not an issue just a question?

### ISSUE THREAD

**Issue by JeanPierreFig** [prahladyeri/hotspotd#41]
How would I go about to configure a domain name for the hotspot? Example, instead of directing a user to use an IP address go to doSomthing.com and that would redirect them to localhost.

**Comment by prahladyeri** [comment]
If you can understand python, see:

https://github.com/prahladyeri/hotspotd/blob/master/main.py

The start_router() function is where the dnsmasq is configured and the AP is started.

**Comment by JeanPierreFig** [comment]
I thought you could do a DNS lookup with dnsmasq.  interesting thank you, I just thought that could be a good add-on. 👍

**Comment by prahladyeri** [comment]
Yes, it does the look up from IP-addresses (like `192.168.45.50`) to the wifi interface on a machine called "Foo" in your local network where `hotspotd` is running (which could be running the dns-server with the ip address `192.168.45.1`). From your question, it looks like you want the hotspot to direct the user to another domain such as xyz.com instead of this local address 192.168.45.1?

If so, then once you connect to the internet using the hotspot, you can directly do so using your mobile browser, a VPN app or a similar tool. There is no need to involve dnsmasq for that.

**Comment by JeanPierreFig** [comment]
Hey, I just saw this. I think you didn't understand me. What I want to do is be able to direct a user that is connected to the hotspot to use the URL setup.com then that URL will redirect to 192.168.45.1 That way the user does not need to type in 192.168.45.1..

**Comment by prahladyeri** [comment]
In that case, that might be possible by changing the DNS configuration on the machine where hotspotd is running (and associate your `setup.com` domain with the IP address 192.168.45.1). See [this stack exchange discussion](https://serverfault.com/questions/136332/setting-up-dnsmasq-for-a-local-network)  for more info.

**Comment by JeanPierreFig** [comment]
Thanks will get back to you when I figure it out. I don't have time right now :(
